# Tensors and neural nets- a gentle introduction :)

In [3]:
# import PyTorch
import torch

In [4]:
# Few examples on tensors to understand their structure 
test1 = torch.randn((1, 5)) # it will give me a one line matrix/ vector, a 1D tensor
test2 = torch.randn((4, 5)) # it will give me a matrix, a 2D tensor

print(test1)
print(test2)

test3 = torch.randn((3, 2, 3)) # it will give me a series of tensors of other tensors with dimension 2x3, a 3D tensor
print(test3)


tensor([[ 1.5423,  1.3192, -0.9794, -0.9501,  0.6271]])
tensor([[ 0.5561, -1.6253, -0.5416,  0.1841,  1.4455],
        [ 0.1039,  0.2703,  0.6547,  0.7677,  1.5010],
        [ 1.9918, -0.3678,  0.3717,  1.2265, -0.4288],
        [ 0.3938,  1.2642,  0.2852, -0.0288, -0.1137]])
tensor([[[-1.1147, -0.2965,  0.6244],
         [ 1.5739,  1.1801,  1.7625]],

        [[-0.4741,  0.0129,  0.2843],
         [ 0.6897,  1.4671,  0.2356]],

        [[ 0.0891, -1.7094,  0.6834],
         [-1.9033, -1.0686,  1.1145]]])


In [5]:
# Example of inside sum for a tensor according to the dimension chosen, see how it works

#test4 is a tensor of other 3 tensors each one having 2x3 dimension

test4 = torch.tensor([
     [
       [1, 2, 3],
       [4, 5, 6]
     ],
     [
       [1, 2, 3],
       [4, 5, 6]
     ],
     [
       [1, 2, 3],
       [4, 5, 6]
     ]
   ])

calapse_tensors = torch.sum(test4, dim=0) #it will sum on the level of the "slices"= tensors, it will colapse the slices
print(calapse_tensors)

calapse_rows = torch.sum(test4, dim=1) 
# it will sum on the level of all rows per tensor, sum(rows from tensor1) then sum(rows from tensor 2) etx, 
# imagine the image of colapsiong the rows per each tensor
print(calapse_rows)

colapse_columns = torch.sum(test4, dim=2)
#it will sum on the level of all columns per tensor, sum(columns from tensor 1) etc, iit will colapse the columns per tensor
print(colapse_columns)

tensor([[ 3,  6,  9],
        [12, 15, 18]])
tensor([[5, 7, 9],
        [5, 7, 9],
        [5, 7, 9]])
tensor([[ 6, 15],
        [ 6, 15],
        [ 6, 15]])


OBS: A good source for visualizing the sum within a tensor's elements (depending on the dimension chosen) is [`HERE`](https://towardsdatascience.com/understanding-dimensions-in-pytorch-6edf9972d3be)


### <strong> Note 1</strong> : Broadcasting conditions: 

1. Each tensor has at least one dimension.
2. When iterating over the dimension sizes, starting at the trailing dimension, the dimension sizes must either be equal, one of them is 1, or one of them does not exist.

In [67]:
# Check for broadcasting situation in matmul function

# test5 = torch.randn(1, 3, 4, 1)
# print(test5)

# test6 = torch.randn(3, 1, 1)
# print(test6)

test5 = torch.randn(1, 2, 4, 1)
print(test5)

test6 = torch.randn(2, 1, 1)
print(test6)

torch.matmul(test5, test6).size()
print(torch.matmul(test5, test6))


tensor([[[[-1.2605],
          [ 0.6978],
          [ 0.4193],
          [ 0.3149]],

         [[-1.0690],
          [-0.2535],
          [ 1.6775],
          [ 1.0760]]]])
tensor([[[-2.1533]],

        [[ 0.1137]]])
tensor([[[[ 2.7143],
          [-1.5025],
          [-0.9028],
          [-0.6780]],

         [[-0.1216],
          [-0.0288],
          [ 0.1908],
          [ 0.1224]]]])


## Coming back to the calculation output for one layer 

In [53]:
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))


### <strong> Note 2: </strong> 
I will choose between more ways of having the vector column  ([`source`](https://pytorch.org/docs/stable/notes/broadcasting.html#broadcasting-semantics)):
1. input_tensor.reshape (find put more about it), 
2. input_tensor.resize_ which is an  in place operation that changes directly the content of a tensor
3. or input_tensor.view, which will give a new tensor with the same input tensor data. 

Here is a great forum thread to [read more about in-place operations](https://discuss.pytorch.org/t/what-is-in-place-operation/16244) in PyTorch.

There are a few options here: [`weights.reshape()`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.reshape), [`weights.resize_()`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.resize_), and [`weights.view()`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.view).

In [95]:
### Generate some data
data = torch.manual_seed(7) # Set the random seed so things are predictable
print(data)

# Features are 5 random normal variables
features = torch.randn((1, 5)) # a tensor matrix 1x5 dimension, randomly generated according to the N(0,1)
print(features)
print(features.size())

# True weights for our data, random normal variables again
weights = torch.randn_like(features)
print(weights)

# change the shape of one line matrix tensor of weights to one column dimension 
# for doing later the matrix method of multiplication
print(weights.view(5,1))

# and a true bias term(a tensor as wel)
bias = torch.randn((1, 1))

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
torch.Size([1, 5])
tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])


In [96]:
## Calculate the output of this network using the weights and bias tensors  (it works because we are dealing with vectors !!!!)
y1 = activation(torch.sum(features * weights) + bias)
# OR
y2 = activation((features * weights).sum() + bias)

# y1 = activation(sum(torch.matmul(features, column_weights), bias))

y3= activation(torch.mm(features, weights.view(5,1))+ bias)
# OR 
y33 = activation(torch.matmul(features, weights.view(5,1)) + bias)

y333 = activation(sum(torch.matmul(features, weights.view(5,1)), bias))

print(y3, y33, y333, y1, y2)

tensor([[0.1595]]) tensor([[0.1595]]) tensor([[0.1595]]) tensor([[0.1595]]) tensor([[0.1595]])


In [36]:
## !!! Calculate the output of a node in the network using matrix multiplication ,  
# BUT matmul broatcasts (it allows operations between diferrent sizes of tensor under some conditions, see Note 1 above)
tensor1 = torch.randn(2, 3, 4)
tensor2 = torch.randn(4,1)
print(tensor1, tensor2)
torch.matmul(tensor1, tensor2).size()
print(torch.matmul(tensor1, tensor2))


tensor([[[-0.1782, -0.2595, -0.0145, -0.3839],
         [-2.9662, -1.0606, -0.3090,  0.9343],
         [ 1.5496,  0.5989, -0.6377, -2.2858]],

        [[-0.3677, -0.8822,  0.5460,  0.1485],
         [-0.7557,  0.3917,  0.7470,  1.3798],
         [ 1.2877,  0.8684, -1.3822, -0.9632]]]) tensor([[ 0.1072],
        [ 0.6125],
        [ 0.3296],
        [-0.8763]])
tensor([[[ 0.1536],
         [-1.8883],
         [ 2.3258]],

        [[-0.5299],
         [-0.8039],
         [ 1.0585]]])


In [33]:

# torch.Size([3, 4, 5])

More on <strong> [Matmul examples](https://pytorch.org/docs/stable/torch.html#torch.matmul)</strong>

## When having more than one layer 

In [60]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn([1, 3]) # we have a 2D tensor
print(features.shape)

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
print(n_input)

n_hidden = 2                    # Number of hidden units, we will have 2 nodes in the hidden layer
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
print(W1.shape)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)
print(W2)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
print(B1)
B2 = torch.randn((1, n_output))

torch.Size([1, 3])
3
torch.Size([3, 2])
tensor([[-1.6822],
        [ 0.3177]])
tensor([[0.1328, 0.1373]])


## Calculate the output (having one hidden layer with 2 nodes)

### Note 3 : 
1. h will be the hidden layer with 2 nodes;

2. h is a tensor resulted from the activation function applied to (features * W1 + B1);

3. output is a tensor resulted from teh activation function applied to (h * W2 + B2)

In [66]:
h = activation(torch.mm(features, W1) + B1)
print(h)
Y= activation(torch.mm(h, W2) + B2)
print(Y)

tensor([[0.6813, 0.4355]])
tensor([[0.3171]])


### Note  4: Shape vs Size of tensors: 
Have a look [here](https://stackoverflow.com/questions/56856996/difference-in-shape-of-tensor-torch-size-and-torch-size1-in-pytorch)

In [7]:
t1 = torch.tensor(5)
print(t1, t1.shape) # tensor(n),  torch.Size([])

t11= torch.tensor([5,6]) # a 1D tensor
print(t11, t11.shape)
print(t11.shape[0])

t12= torch.tensor([[5,6]]) #a 2D tensor, it is taken as tensor[1,2]
print(t12, t12.shape)
print(t12.shape[0])

t13= torch.tensor((1,3)) # a 1D tensor
print(t13, t11.shape)
print(t13.shape[0])


tensor(5) torch.Size([])
tensor([5, 6]) torch.Size([2])
2
tensor([[5, 6]]) torch.Size([1, 2])
1
tensor([1, 3]) torch.Size([2])
2


In [ ]:
t2 = torch.tensor([[5, 4, 6, 7],[1, 5, 7, 9]])
print(t2, t2.shape) # tensor([n]) torch.Size([1])
print(t2.shape[0]) # 1 is for the second dimension meaning 2 tensors as elements
print(t2.shape[1]) 
# shape takes the number of elements along a dimension, 0 is for the first dimension, meaning 4 elements within each tensor
# shape[position] works like an array's positions 

t3 = torch.tensor([[10,2], [5,3], [11,5]])
print(t3, t3.shape) # torch.Size([3,2])
print(t3.shape[0]) # 3, as number of tensors elements 
print(t3.shape[1]) # 2 as number of elements within the individual tensor


In [48]:
t4 = torch.tensor([[[10],[5]],[[4], [5]], [[5],[7]]]) # a 3D tensor
print(t4, t4.shape) #  torch.Size([3, 2, 1])
print(t4.shape[0])
print(t4.shape[1])
print(t4.shape[2])

t = torch.unsqueeze(t4, 0) # a 4D tensor, the second argument in unsqueeze add an extra dimension, 
# in this case 0 means 1 tensor of other 2 tensors of dimension 1x1
print(t, t.shape) #  torch.Size([1, 3, 2, 1])
print(t.shape[0])
print(t.shape[1])
print(t.shape[2])
print(t.shape[3])

tensor([[[10],
         [ 5]],

        [[ 4],
         [ 5]],

        [[ 5],
         [ 7]]]) torch.Size([3, 2, 1])
3
2
1
tensor([[[[10],
          [ 5]],

         [[ 4],
          [ 5]],

         [[ 5],
          [ 7]]]]) torch.Size([1, 3, 2, 1])
1
3
2
1


### Switching between Numpy's arrays and Pytorch's tensors

In [72]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.78868662, 0.73321195, 0.47463454],
       [0.3379168 , 0.85028137, 0.99561204],
       [0.54409091, 0.66113114, 0.93360019],
       [0.25007664, 0.11012498, 0.82379173]])

In [73]:
b = torch.from_numpy(a) 
b # is the array a transformed into a tensor

tensor([[0.7887, 0.7332, 0.4746],
        [0.3379, 0.8503, 0.9956],
        [0.5441, 0.6611, 0.9336],
        [0.2501, 0.1101, 0.8238]], dtype=torch.float64)

In [76]:
b.numpy() # I bring back the tensor b into a numpy array


array([[1.57737324, 1.46642389, 0.94926907],
       [0.67583361, 1.70056273, 1.99122408],
       [1.08818182, 1.32226228, 1.86720038],
       [0.50015328, 0.22024995, 1.64758346]])

In [77]:
b.mul_(2) # an in place operation that changes the orginal tensor

tensor([[3.1547, 2.9328, 1.8985],
        [1.3517, 3.4011, 3.9824],
        [2.1764, 2.6445, 3.7344],
        [1.0003, 0.4405, 3.2952]], dtype=torch.float64)

In [78]:
a  # a has changed as well after the change of "its" tensor

array([[3.15474647, 2.93284778, 1.89853815],
       [1.35166722, 3.40112547, 3.98244815],
       [2.17636364, 2.64452456, 3.73440075],
       [1.00030656, 0.4404999 , 3.29516692]])